-- Q7: Net revenue generated by the company, and quarter-over-quarter % change
SELECT
    quarter_number,
    SUM(vehicle_price * quantity * (1 - discount)) AS net_revenue,
    LAG(SUM(vehicle_price * quantity * (1 - discount)), 1, 0)
        OVER (ORDER BY quarter_number) AS previous_quarter_revenue,
    (SUM(vehicle_price * quantity * (1 - discount))
        - LAG(SUM(vehicle_price * quantity * (1 - discount)), 1, 0) OVER (ORDER BY quarter_number))
        * 100.0
        / LAG(SUM(vehicle_price * quantity * (1 - discount)), 1, 0) OVER (ORDER BY quarter_number)
        AS qoq_percentage_change
FROM
    order_t
GROUP BY
    quarter_number
ORDER BY
    quarter_number;

-- Result: Q1: $18.03M | Q2: $13.12M (-27.23% QoQ) | Q3: $8.88M (-32.32% QoQ) | Q4: $8.57M (-3.48% QoQ)
-- Insight: Net revenue is declining every quarter; Q3 saw the sharpest drop (-32.32%).
